#!/bin/sh

if [ $# -ne 3 ]
then
  echo "grep-range: usage: pattern0 pattern1 file" 1>&2
  exit 111
fi

pattern0="$1"
pattern1="$2"
file="$3"
matched=0

IFS="
"

for line in `cat ${file}`
do
  echo "${line}" | egrep "${pattern0}" >/dev/null
  case $? in
    0) matched=1;;
    1) ;;
    *) exit 112;;
  esac
  if [ ${matched} -eq 1 ]
  then
    echo "${line}"
    echo "${line}" | egrep "${pattern1}" >/dev/null
    case $? in
      0) exit 0;;
      1) ;;
      *) exit 112;;
    esac
  fi
done
